import React, { useEffect, useRef } from "react";
import { useLocation } from "react-router-dom";
import {
  FaMapMarkerAlt,
  FaPhoneAlt,
  FaEnvelope,
  FaClock,
  FaHeadset,
  FaLock,
  FaUserTie,
} from "react-icons/fa";


export default function TermsAndConditions() {
  const location = useLocation();
  const privacyRef = useRef(null);

  useEffect(() => {
    if (location.hash === "#terms") {
      // Scroll to very top of the page
      window.scrollTo({ top: 0, behavior: "auto" });
    } else if (location.hash === "#privacy" && privacyRef.current) {
      // Scroll to privacy section
      privacyRef.current.scrollIntoView({ behavior: "smooth" });
    }
  }, [location]);

  return (
    <div className="bg-blue-100 min-h-screen py-10 px-4 font-lato">
      <div className="max-w-4xl mx-auto bg-white/90 shadow-xl rounded-xl px-10 py-8 text-gray-800 mt-24 hover:shadow-2xl">
        <div id="terms">
          <h1 className="text-3xl sm:text-4xl font-bold text-blue-800 mb-6 text-center">
            Terms & Conditions and Privacy Policy
          </h1>

          <p className="text-lg font-semibold text-gray-800 mb-4">
            Terms & Conditions

          </p>

          <p className="mb-4 text-base text-gray-700 leading-relaxed">
            This document is an electronic record in terms of the Information Technology Act, 2000 and the rules made thereunder, as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </p>

          <p className="mb-4 text-base text-gray-700 leading-relaxed">
            {/* Welcome to <strong>Legafin.org</strong> is owned and managed by OS
          Consulting Services LLP (herein after referred to as Legafin) a
          company duly incorporated under the provisions of the Companies Act,
          2013. If you continue to browse and use this website you are agreeing
          to comply with and be bound by the following terms and conditions of
          use, which together with our privacy policy govern
          Legafin.org/Legafin's relationship with you in relation to this
          website. */}
            Welcome to <strong>Legafin.org.</strong>  The website is owned and managed by OS Consulting Services LLP (hereinafter referred to as "Legafin"), a limited liability partnership incorporated under the Limited Liability Partnership Act, 2008. By continuing to browse and use this website, you agree to comply with and be bound by the following terms and conditions of use, which together with our Privacy Policy govern Legafin's relationship with you in relation to this website.
          </p>

          <p className="mb-4 text-base text-gray-700 leading-relaxed">
            {/* The term <strong> 'Legafin'</strong> or <strong>'us'</strong> or{" "}
          <strong>'we'</strong> refers to the owner of the website whose
          registered office is 29 Block-D-3 S/F Pocket-8, Sector 23-B
          Dwarka,Bagdola, South West Delhi, New Delhi India, 110077. Our LLP
          Identification Number is ACL-2562. The term 'you' refers to the user
          or viewer of our website. */}
            The term <strong>'Legafin'</strong> or <strong>'us'</strong> or <strong>'we'</strong> refers to the owner of the website whose registered office is D3, 29 2nd Floor, Pocket-8, Dwarka Sector 23B, Bagdola, New Delhi, India - 110077. Our LLP Identification Number is ACL-2562. The term 'you' refers to the user or viewer of our website.
          </p>

          {/* Section 1 */}
          <h2 className="text-lg font-semibold mt-8 mb-3 text-blue-900">
            The use of this website is subject to the following terms of use:
          </h2>
          <ul className="list-disc pl-12 pr-12 space-y-2 text-base text-gray-700 leading-relaxed">
            <li>
              The content of the pages of this website is for your general
              information and use only. It is subject to change without notice.
            </li>
            <li>
              Neither we nor any third parties provide any warranty or guarantee
              as to the accuracy, timeliness, performance, completeness or
              suitability of the information and materials found or offered on
              this website for any particular purpose. You acknowledge that such
              information and materials may contain inaccuracies or errors and we
              expressly exclude liability for any such inaccuracies or errors to
              the fullest extent permitted by law.
            </li>
            <li>
              Your use of any information or materials on this website is entirely
              at your own risk, for which we shall not be liable. It shall be your
              own responsibility to ensure that any products, services or
              information available through this website meet your specific
              requirements.
            </li>
            <li>
              This website contains material which is owned by or licensed to us.
              This material includes, but is not limited to, the design, layout,
              look, appearance and graphics. Reproduction is prohibited other than
              in accordance with the copyright notice, which forms part of these
              terms and conditions. All trademarks reproduced in this website
              which are not the property of, or licensed to Legafin are
              acknowledged on the website.
            </li>
            <li>
              Unauthorised use of this website may give rise to a claim for
              damages and/or be a criminal offence. From time to time this website
              may also include links to other websites. These links are provided
              for your convenience to provide further information. They do not
              signify that we endorse the website(s). We have no responsibility
              for the content of the linked website(s).
            </li>
            <li>
              You may not create a link to this website from another website or
              document without Legafin's prior written consent. Your use of this
              website and any dispute arising out of such use of the website is
              subject to the laws of India or regulatory authority within the
              country of India.
            </li>
            <li>
              The user understands and agrees that any material or data downloaded
              or otherwise obtained through the Website is done entirely at their
              own discretion and risk and they will be solely responsible for any
              damage to their computer systems or loss of data that results from
              the download of such material or data. Company is not responsible
              for any typographical error leading to an invalid coupon. Company
              accepts no liability for any errors or omissions, with respect to
              any information provided to you whether on behalf of itself or third
              parties. Company shall not be liable for any third party product or
              services. The advertisement available on e-mail or website with
              respect to the third party website or the Products are for
              information purpose only. You expressly agree that Your use of the
              Website is at Your risk.
            </li>
            <li>
              The User agrees to use the service to authorise an individual and
              get the products on his/her behalf.
            </li>
            <li>
              Subject to compliance with these Terms, Company grants You a
              personal, non-exclusive, non-transferable, limited privilege to
              access and use this Website and the services provided herein.
            </li>

          </ul>
          <ul className="mt-6 mb-6 pr-13 text-base text-gray-700 leading-relaxed ">
            <li>
              If Website allows You to post and upload any material on the
              Website, You hereby undertake to ensure that such material is not
              offensive and in accordance with applicable laws. Further, You
              undertake not to:
            </li>
          </ul>
          <ul className="mt-4 pl-10 pr-10 text-base text-gray-700 leading-relaxed">
            <li>
              •	Defame, abuse, harass, threaten or otherwise violate the legal rights of others;
              Impersonate any person or entity, or falsely state or otherwise misrepresent your affiliation with a person or entity;

            </li>
            <li>
              •	Publish, post, upload, distribute or disseminate any inappropriate, profane, defamatory, infringing, obscene, indecent, or unlawful content
            </li>
            <li>
              •	Upload files that contain software or other material protected by intellectual property laws unless you own or control the rights or have received all necessary consents.
            </li>
            <li>
              •	Upload or distribute files that contain viruses, corrupted files, or any similar software that may damage website operations or another user’s computer.
            </li>
          </ul>

          {/* Section 2 */}
          <h2 className="text-lg pl-10 font-semibold mt-8 mb-3 text-blue-900">
            Intellectual Property Rights
          </h2>
          <p className="mb-4 text-base text-gray-700 leading-relaxed pl-10 pr-10">
            The Website and the processes, including their selection and arrangement, including but not limited to all text, graphics, user interfaces, visual interfaces, sounds, music (if any), artwork, and computer code (collectively, the 'Content') are owned and controlled by the Company. This design and structure are protected under copyright, patent, trademark laws, and various other intellectual property rights.
          </p>

          <p className="mb-4 text-base text-gray-700 leading-relaxed pl-10 pr-10">
            The trademarks, logos, and service marks displayed on the Website ("Marks") are the property of the Company or third parties. You are not permitted to use the Marks without the prior consent of the Company or the relevant third party.
          </p>

          <p className="mb-4 text-base text-gray-700 leading-relaxed pl-10 pr-10">
            Unless otherwise indicated, or unless any proprietary material is explicitly mentioned as belonging to a third party, the Company owns all intellectual property rights to Legafin.org and the Website, including any copyrights, patents, trademarks, trade secrets, source code, databases, meta tags, content, icons, and graphics.
          </p>

          <p className="mb-4 text-base text-gray-700 leading-relaxed pl-10 pr-10">
            Except as expressly permitted, you may not copy, republish, post, display, translate, transmit, or distribute any content without prior written consent.
          </p>

          {/* Section 3 */}
          <h2 className=" pl-10 text-lg font-semibold mt-8 mb-3 text-blue-900">
            Communications
          </h2>
          <p className="mb-4 text-base text-gray-700 leading-relaxed pl-10 pr-10">
            You hereby expressly agree to receive communications from the Company via SMS, email, WhatsApp, and phone calls related to your orders and the services offered through the Website or any affiliates of Legafin.
          </p>
          <div>
            <h1 className=" pl-8 text-lg font-semibold mt-3 mb-1 text-blue-900">
            Service Cancellation and Refund Policy
          </h1>
            
            <ul className="list-disc  text-gray-700 leading-relaxed pl-12 pr-12">
              <h1 className="text-lg font-semibold   mt-3  text-blue-900  ">•	Cancellation Policy</h1>
              <ul className="pl-4 pr-12  mb-3">
              <li>
                Once payment is made and service delivery has been initiated (e.g., documentation reviewed, consultation scheduled, or any preparatory work commenced), cancellation is not permitted. If no such work has started, a cancellation request may be considered on a case-by-case basis.
              </li>
              </ul>

            </ul>
          </div>

          {/* Section 4 */}
          <div >
            
            <ul className="list-disc text-gray-700 leading-relaxed pl-12 pr-12">
              <h1 className="text-lg font-semibold  mt-3  text-blue-900">• Refund Policy</h1>
              <ul>
              <li className="pl-4 pr-12  ">
                For any concerns regarding our services, you may email us at <strong>contact@legafin.org.</strong> Refunds, if any, will be reviewed based on the nature of the service provided, the stage of completion, and any administrative effort already undertaken.
                The final decision regarding refunds rests solely with <strong>Legafin </strong> and will be communicated via email/sms/call.

              </li>
              </ul>

            </ul>
            <p className="pl-10 pr-10 mt-3 mb-3  text-gray-700 leading-relaxed"><strong>Dispute Resolution:</strong> Any disputes arising between the parties shall first be attempted to be resolved through negotiation and mutual understanding. If not resolved, the dispute shall be jurisdiction of the courts in Delhi.</p>

          </div>

          {/* Section 5 */}
          




          {/* Section 6 */}
          <div id="privacy" ref={privacyRef} className="relative -mt-24 pt-24  " >
            <h2 className="text-lg font-semibold mt-8 mb-3 text-blue-900">
              Privacy Policy
            </h2>
            <p className="mb-4 text-gray-700 leading-relaxed pl-10 pr-10">
              This privacy policy sets out how Legafin uses and protects any
              information that you provide to Legafin when you use this website.
            </p>
            <p className="mb-4 text-gray-700 leading-relaxed pl-10 pr-10">
              Legafin is committed to ensuring that your privacy is protected.
              Should we ask you to provide certain information by which you can be
              identified when using this website, then you can be assured that it
              will only be used in accordance with this privacy statement.{" "}
            </p>
            <p className="mb-4 text-gray-700 leading-relaxed pl-10 pr-10">
              Legafin may change this policy from time to time by updating this
              page. You should check this page from time to time to ensure that you
              are happy with any changes. This policy is revised and effective from
              01/08/2026.{" "}
            </p>

            <p className="mb-2 text-gray-700 leading-relaxed pl-10 pr-10">
              What we collect: We may collect the following information
            </p>
            <div className=" pl-12 pr-12" >

            <ul className="list-disc  space-y-2 text-gray-700 leading-relaxed">
              <li>Name and Job title</li>
              <li>Contact Information including email address & phone number</li>
              <li>
                Demographic Information such as City, postcode, preferences and
                interests
              </li>
              <li>
                Other Information relevant to service enquiry, customer surveys
                and/or offers
              </li>
            </ul>
            </div>

            {/* Section 7 */}
            <h2 className="text-lg font-semibold mt-8 mb-3 text-blue-900">
              What we do with the information we gather
            </h2>
            <p className="mb-4 text-gray-700 leading-relaxed pl-10 pr-10">
              We require this information to understand your needs and provide you
              with a best service, and in particular for the following reasons:
            </p>
            <ul className="list-disc  space-y-2 text-gray-700 leading-relaxed pl-12 pr-12">
              <li>Internal record keeping.</li>
              <li>
                We may use the information to improve our products and services.
              </li>
              <li>
                We may periodically send promotional emails about new products,
                special offers or other information which we think you may find
                interesting using the email address which you have provided.
              </li>
              <li>
                From time to time, we may also use your information to contact you
                for feedback, market research purposes. We may contact you by email,
                phone, fax or mail. We may use the information to customise the
                website according to your interests.
              </li>
            </ul>

            {/* Section 8 */}
            <h2 className="text-lg font-semibold mt-8 mb-3 text-blue-900">
              Security
            </h2>
            <p className="mb-4 text-gray-700 leading-relaxed pl-10 pr-10">
              We are committed to ensuring that your information is secure. In order
              to prevent unauthorised access or disclosure we have put in place
              suitable physical, electronic and managerial procedures to safeguard
              and secure the information we collect online.
            </p>

            {/* Section 9 */}
            <h2 className="text-lg font-semibold mt-8 mb-3 text-blue-900">
              How we use cookies
            </h2>
            <p className="mb-4 text-gray-700 leading-relaxed pl-10 pr-10">
              A cookie is a small file which asks permission to be placed on your
              computer's hard drive. Once you agree, the file is added and the
              cookie helps analyse web traffic or lets you know when you visit a
              particular site. Cookies allow web applications to respond to you as
              an individual. The web application can tailor its operations to your
              needs, likes and dislikes by gathering and remembering information
              about your preferences. We use traffic log cookies to identify which
              pages are being used. This helps us analyse data about webpage traffic
              and improve our website in order to tailor it to customer needs. We
              only use this information for statistical analysis purposes and then
              the data is removed from the system.
            </p>

            <p className="mb-4 text-gray-700 leading-relaxed pl-10 pr-10">
              We are committed to ensuring that your information is secure. In order
              to prevent unauthorised access or disclosure we have put in place
              suitable physical, electronic and managerial procedures to safeguard
              and secure the information we collect online.
            </p>

            {/* Section 9 */}
            <h2 className="text-lg font-semibold mt-8 mb-3 text-blue-900">
              How we use cookies
            </h2>
            <p className="mb-4 text-gray-700 leading-relaxed pl-10 pr-10">
              A cookie is a small file which asks permission to be placed on your
              computer's hard drive. Once you agree, the file is added and the
              cookie helps analyse web traffic or lets you know when you visit a
              particular site. Cookies allow web applications to respond to you as
              an individual. The web application can tailor its operations to your
              needs, likes and dislikes by gathering and remembering information
              about your preferences. We use traffic log cookies to identify which
              pages are being used. This helps us analyse data about webpage traffic
              and improve our website in order to tailor it to customer needs. We
              only use this information for statistical analysis purposes and then
              the data is removed from the system.
            </p>

            <p className="mb-4 text-gray-700 leading-relaxed pl-10 pr-10">
              Overall, cookies help us provide you with a better website, by
              enabling us to monitor which pages you find useful and which you do
              not. A cookie in no way gives us access to your computer or any
              information about you, other than the data you choose to share with
              us. You can choose to accept or decline cookies. Most web browsers
              automatically accept cookies, but you can usually modify your browser
              setting to decline cookies if you prefer. This may prevent you from
              taking full advantage of the website.
            </p>

            {/* Section 10 */}
            <h2 className="text-lg font-semibold mt-8 mb-3 text-blue-900">
              General Provisions
            </h2>
            <p className="mb-4 text-gray-700 leading-relaxed pl-10 pr-10">
              <strong>Assignment:</strong> You cannot assign or otherwise transfer
              the Terms, or any rights granted hereunder to any third party.
              Company's rights under the Terms are freely transferable by Company to
              any third parties without the requirement of seeking your consent.
            </p>

            <p className="mb-4 text-gray-700 leading-relaxed pl-10 pr-10">
              <strong>Severability:</strong> If, for any reason, a court of
              competent jurisdiction finds any provision of these Terms, or portion
              thereof, to be unenforceable, that provision shall be enforced to the
              maximum extent permissible so as to give effect to the intent of the
              parties as reflected by that provision, and the remainder of the Terms
              shall continue in full force and effect.
            </p>
            <p className="mb-4 text-gray-700 leading-relaxed pl-10 pr-10">
              <strong>Waiver:</strong> Any failure by Company to enforce or exercise
              any provision of the Terms, or any related right, shall not constitute
              a waiver by Company of that provision or right.
            </p>

            {/* Section 11 */}
            <h2 className="text-lg font-semibold mt-8 mb-3 text-blue-900">
              Links to other websites
            </h2>
            <p className="mb-4 text-gray-700 leading-relaxed pl-10 pr-10">
              Our website may contain links to other websites of interest. However,
              once you have used these links to leave our site, you should note that
              we do not have any control over that other website. Therefore, we
              cannot be responsible for the protection and privacy of any
              information which you provide whilst visiting such sites and such
              sites are not governed by this privacy statement. You should exercise
              caution and look at the privacy statement applicable to the website in
              question.
            </p>

            {/* Section 12 */}
            <h2 className="text-lg font-semibold mt-8 mb-3 text-blue-900">
              Controlling your Personal Information
            </h2>
            <p className="mb-4 text-gray-700 leading-relaxed pl-10 pr-10">
              You may choose to restrict the collection or use of your personal
              information in the following ways:
            </p>
            <ul className="list-disc  space-y-2 text-gray-700 leading-relaxed pl-12 pr-12">
              <li>
                Whenever you are asked to fill in a form on the website, look for
                the box that you can click to indicate that you do not want the
                information to be used by anybody for promotional purposes. If such
                box is not available, you may choose not to fill such form. However,
                by submitting the filled enquiry form, you will be construed to have
                foregone your right and Company may choose to send promotional
                emails and materials from time to time.
              </li>
              <li>
                If you have previously agreed to us using your personal information
                for promotional purposes, you may change your mind at any time by
                writing to or emailing us at contact@Legafin.org
              </li>
            </ul>
            <p className="mb-4  mt-2 text-gray-700 leading-relaxed pl-12 pr-12">
              We will not sell, distribute or lease your personal information to
              third parties unless we have your permission or are required by law to
              do so. We may use your personal information to send you promotional
              information about third parties which we think you may find
              interesting.
            </p>

            {/* Section 13 */}

            <p className="mb-2 text-gray-700 leading-relaxed pl-12 pr-12">
              If there are any questions regarding this privacy policy you may
              contact us using the information below:
            </p>
            <h3 className="text-2xl mb-3 mt-3 font-bold text-blue-900">
              Contact Us
            </h3>
            <ul className="space-y-3 text-gray-700 text-[1rem] leading-relaxed">
              <li className="flex items-start gap-5">
                {/* <FaMapMarkerAlt className="text-blue-800 mt-1" />
                <span className="text-gray-500">
                  D3, 29, 2nd Floor, DDA Golf Link, Dwarka Sec 23B Delhi
                  110077
                </span> */}
              </li>
              <li className="flex items-start gap-5">
                <FaPhoneAlt className="text-blue-800 mt-1" />
                <span className="text-gray-500">+91 9990295002</span>
              </li>
              <li className="flex items-start gap-5">
                <FaEnvelope className="text-blue-800 mt-1" />
                <span className="text-gray-500">contact@legafin.org</span>
              </li>
              <li className="flex items-start gap-5">
                <FaClock className="text-blue-800 mt-1" />
                <span className="text-gray-500">Mon – Sat: 10 AM – 6 PM</span>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};


